<a href="https://colab.research.google.com/github/Shreyareddya/nlp-lab/blob/main/NLP3_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
data = pd.read_csv('/content/twitter4000.csv')

In [ ]:
data

                                                 twitts  sentiment
0     is bored and wants to watch a movie  any sugge...          0
1              back in miami.  waiting to unboard ship           0
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                     ughhh i am so tired  blahhhhhhhhh          0
4     @mandagoforth me bad! It's funny though. Zacha...          0
...                                                 ...        ...
3995                                  i just graduated           1
3996          Templating works; it all has to be done            1
3997                   mommy just brought me starbucks           1
3998  @omarepps watching you on a House re-run...lov...          1
3999  Thanks for trying to make me smile I'll make y...          1

[4000 rows x 2 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   twitts     4000 non-null   object
 1   sentiment  4000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 62.6+ KB

In [ ]:
data.count()

twitts       4000
sentiment    4000
dtype: int64

In [ ]:
data['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [ ]:
data.head()

                                              twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [ ]:
data.tail()

                                                 twitts  sentiment
3995                                  i just graduated           1
3996          Templating works; it all has to be done            1
3997                   mommy just brought me starbucks           1
3998  @omarepps watching you on a House re-run...lov...          1
3999  Thanks for trying to make me smile I'll make y...          1

In [ ]:
pattern = r'\s'
data['twitts'].apply(lambda x: re.sub(pattern, '', x))

0             isboredandwantstowatchamovieanysuggestions?
1                        backinmiami.waitingtounboardship
2       @misskpeyawwwwdntdisbrngbakmemoriessss,IthnkI'...
3                             ughhhiamsotiredblahhhhhhhhh
4       @mandagoforthmebad!It'sfunnythough.ZacharyQuin...
                              ...
3995                                       ijustgraduated
3996                     Templatingworks;itallhastobedone
3997                          mommyjustbroughtmestarbucks
3998        @omareppswatchingyouonaHousere-run...lovinit.
3999    ThanksfortryingtomakemesmileI'llmakeyour18thsp...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'\s'
data['char_count']= data['twitts'].apply(lambda x: len(re.sub(pattern, '', x)))

In [ ]:
data

                                                 twitts  sentiment  char_count
0     is bored and wants to watch a movie  any sugge...          0          43
1              back in miami.  waiting to unboard ship           0          32
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0          54
3                     ughhh i am so tired  blahhhhhhhhh          0          27
4     @mandagoforth me bad! It's funny though. Zacha...          0         116
...                                                 ...        ...         ...
3995                                  i just graduated           1          14
3996          Templating works; it all has to be done            1          32
3997                   mommy just brought me starbucks           1          27
3998  @omarepps watching you on a House re-run...lov...          1          45
3999  Thanks for trying to make me smile I'll make y...          1          63

[4000 rows x 3 columns]

In [ ]:
data['word_count']= data['twitts'].apply(lambda x: len(x.split()))

In [ ]:
data

,twitts,sentiment,char_count,word_count
0,is bored and wants to watch a movie any sugge...,0,43,10
1,back in miami. waiting to unboard ship,0,32,7
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12
3,ughhh i am so tired blahhhhhhhhh,0,27,6
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26
...,...,...,...,...
3995,i just graduated,1,14,3
3996,Templating works; it all has to be done,1,32,8
3997,mommy just brought me starbucks,1,27,5
3998,@omarepps watching you on a House re-run...lov...,1,45,8
3999,Thanks for trying to make me smile I'll make y...,1,63,16

In [ ]:
data['avg_word_length']=data['char_count']/data['word_count']

In [ ]:
data

,twitts,sentiment,char_count,word_count,avg_word_length
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000
1,back in miami. waiting to unboard ship,0,32,7,4.571429
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538
...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667
3996,Templating works; it all has to be done,1,32,8,4.000000
3997,mommy just brought me starbucks,1,27,5,5.400000
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500

In [ ]:
data['hash_tags_count']=data['twitts'].apply(lambda x: len(re.findall(r'#\w+', x)))
data

,twitts,sentiment,char_count,word_count,avg_word_length,hash_tags_count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0
...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0
3996,Templating works; it all has to be done,1,32,8,4.000000,0
3997,mommy just brought me starbucks,1,27,5,5.400000,0
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0

In [ ]:
data['mention_count']=data['twitts'].apply(lambda x: len(re.findall(r'@\w+', x)))
data

,twitts,sentiment,char_count,word_count,avg_word_length,hash_tags_count,mention_count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0,0
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0,0
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0,0
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1
...,...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0,0
3996,Templating works; it all has to be done,1,32,8,4.000000,0,0
3997,mommy just brought me starbucks,1,27,5,5.400000,0,0
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0,1
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0,0

In [ ]:
data['twitts'].apply(lambda x: len([word for word in x.split() if word.isupper()]))

0       0
1       0
2       1
3       0
4       0
       ..
3995    0
3996    0
3997    0
3998    0
3999    0
Name: twitts, Length: 4000, dtype: int64

In [ ]:
data['twitts'].apply(lambda x: re.sub(r'\s+','',x).lower())

0             isboredandwantstowatchamovieanysuggestions?
1                        backinmiami.waitingtounboardship
2       @misskpeyawwwwdntdisbrngbakmemoriessss,ithnki'...
3                             ughhhiamsotiredblahhhhhhhhh
4       @mandagoforthmebad!it'sfunnythough.zacharyquin...
                              ...
3995                                       ijustgraduated
3996                     templatingworks;itallhastobedone
3997                          mommyjustbroughtmestarbucks
3998        @omareppswatchingyouonahousere-run...lovinit.
3999    thanksfortryingtomakemesmilei'llmakeyour18thsp...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern=r'@\w+'
data['twitts'].apply(lambda x: re.sub(pattern,'',x))

0       is bored and wants to watch a movie  any sugge...
1                back in miami.  waiting to unboard ship
2        awwww dnt dis brng bak memoriessss,  I thnk I...
3                       ughhh i am so tired  blahhhhhhhhh
4        me bad! It's funny though. Zachary Quinto is ...
                              ...
3995                                    i just graduated
3996            Templating works; it all has to be done
3997                     mommy just brought me starbucks
3998          watching you on a House re-run...lovin it.
3999    Thanks for trying to make me smile I'll make y...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'\s'
data['twitts'].apply(lambda x: re.sub(pattern,'',x))

0             isboredandwantstowatchamovieanysuggestions?
1                        backinmiami.waitingtounboardship
2       @misskpeyawwwwdntdisbrngbakmemoriessss,IthnkI'...
3                             ughhhiamsotiredblahhhhhhhhh
4       @mandagoforthmebad!It'sfunnythough.ZacharyQuin...
                              ...
3995                                       ijustgraduated
3996                     Templatingworks;itallhastobedone
3997                          mommyjustbroughtmestarbucks
3998        @omareppswatchingyouonaHousere-run...lovinit.
3999    ThanksfortryingtomakemesmileI'llmakeyour18thsp...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern=r'w+@\w+.\w+'

In [ ]:
data['email']=data['twitts'].apply(lambda x: re.findall(pattern=pattern,string=x))

In [ ]:
pattern=r'\b\b'

In [ ]:
data['email'].sample(5)

3689                             [, , , , , , , , , , , ]
665     [, , , , , , , , , , , , , , , , , , , , , , ,...
3925    [, , , , , , , , , , , , , , , , , , , , , , ,...
600     [, , , , , , , , , , , , , , , , , , , , , , ,...
31               [, , , , , , , , , , , , , , , , , , , ]
Name: email, dtype: object

In [ ]:
pattern= r'\b[A-Za-z._+-]+@[A-Za-z.].[A-Z|a-z]{2,}\b'

In [ ]:
data['email'].count()
np.int64(4000)
data['email'].value_counts()

email
[, , , , , , , , , , , , , ]                                                                                                                                                                                     204
[, , , , , , , , , , , , , , , , , ]                                                                                                                                                                             203
[, , , , , , , , , , , , , , , , , , , ]                                                                                                                                                                         199
[, , , , , , , , , , , ]                                                                                                                                                                                         199
[, , , , , , , , , , , , , , , ]                                                                                                                                                                                 195
[, , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                                                     191
[, , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                                                 185
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                                     183
[, , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                                         178
[, , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                                             174
[, , , , , , , ]                                                                                                                                                                                                 168
[, , , , , , , , , ]                                                                                                                                                                                             165
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                         160
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                     148
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                                 146
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                             144
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                     134
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                                 119
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                         117
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                             113
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                                 110
[, , , , , ]                                                                                                                                                                                                     100
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                              88
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                          83
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                      80
[, , , ]                                                                                                                                                                                                          64
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                                  49
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                              39
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                          26
[, ]                                                                                                                                                                                                              14
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                      12
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                                   6
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                               2
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ]                                                                           1
[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ...]      1
Name: count, dtype: int64

In [ ]:
data['email']=data['twitts'].apply(lambda x: re.findall(pattern=pattern,string=x))

In [ ]:
data['email']

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: email, Length: 4000, dtype: object

In [ ]:
pattern = r'\b[A-za-z0-9._%+-]+@[A-ZA-za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
data['email']= data['twitts'].apply(lambda x: "," . join(re.findall(pattern = pattern, string = x)))
data['email']

0
1
2
3
4
       ..
3995
3996
3997
3998
3999
Name: email, Length: 4000, dtype: object

In [ ]:
data['email'].value_counts()

email
                               3999
markbradbury_16@hotmail.com       1
Name: count, dtype: int64

In [ ]:
pattern = r'\b[A-za-z0-9._%+-]+@[A-ZA-za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
data['email']= data['twitts'].apply(lambda x: "," . join(re.findall(pattern = pattern, string = x)))
data['email_count']=data['twitts'].apply(lambda x: x.count(',')+1 if len(x)>0 else 0)

In [ ]:
data.head()

,twitts,sentiment,char_count,word_count,avg_word_length,hash_tags_count,mention_count,email,email_count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0,0,,1
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0,0,,1
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1,,2
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0,0,,1
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1,,1